name: unit/build tests

on: [push, pull_request]

jobs:
  # job name
  build_and_unit_test:

    # Run on Ubuntu
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    name: Build examples and tests; run tests

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: build examples and tests
        run: |
          A2D_ROOT=$(pwd);
          mkdir ${A2D_ROOT}/build;
          cd ${A2D_ROOT}/build;
          cmake .. -DCMAKE_BUILD_TYPE=Release -DA2D_BUILD_EXAMPLES=ON -DA2D_BUILD_TESTS=ON;
          make -j;

      - name: run unit tests
        run: |
          cd build/tests;
          ctest;
